apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/argocd-k8s-apps.git
    targetRevision: HEAD
    path: clusters/dev-cluster/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
