apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-cluster-appset
  namespace: argocd
spec:
  generators:
    - directory:
        path: clusters/dev-cluster/apps
        repoURL: 'https://github.com/BBrucelee2002/gitops-k8s-apps.git'
        targetRevision: HEAD
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/BBrucelee2002/gitops-k8s-apps.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
