apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io   # <-- Enables deletion of cluster resources
spec:
  project: default
  source:
    repoURL: 'https://github.com/BBrucelee2002/gitops-k8s-apps.git'
    targetRevision: HEAD
    path: clusters/dev-cluster/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true                        # <-- Ensures namespace deletion happens last
